# M2M Agent Runtime ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connector
  namespace: connector-core
  labels:
    app.kubernetes.io/name: connector-core
    app.kubernetes.io/component: agent-runtime
