[package]
name = "payment_channel"
version = "0.1.0"
authors = []

[addresses]
payment_channel = "0xb206e544e69642e894f4eb4d2ba8b6e2b26bf1fd4b5a76cfc0d73c55ca725b6a"  # Deployed to testnet

[dev-addresses]
payment_channel = "0xCAFE"  # Used for testing

[dependencies]
# Pin to mainnet release for reproducible builds
# Update to latest mainnet tag periodically (check: https://github.com/aptos-labs/aptos-core/releases)
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "mainnet" }

[dev-dependencies]
