# M2M Connector Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connector
  namespace: connector
  labels:
    app.kubernetes.io/name: connector
    app.kubernetes.io/component: connector
