# M2M Connector Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connector
  namespace: m2m-connector
  labels:
    app.kubernetes.io/name: m2m-connector
    app.kubernetes.io/component: connector
